# localhostのpostgres接続情報
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ec_y_yasui
#    username: postgres
#    password: postgres
#    
# Herokuのpostgres接続情報(検証済み)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-18-210-51-239.compute-1.amazonaws.com:5432/dauhiubb2sphj?sslmode=require
    username: nlacxersykriau
    password: 4e533dc166cff298a0c755fc7c1aef7a244b1204082845ca16b280e5fc7216d5
    
#  jmx:
#   enabled: false
